name: keepalive
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health
        run: |
          curl -sSfL https://cartography-pjfd.onrender.com/healthz >/dev/null
